[terraform-ansible]
34.219.110.140

# para executar o ansible é necessario executar o senguinte comando

# ansible-playbook playbook.yml -u ubuntu --private-key iac-alura.pem -i hosts.yml

# Comando: ansible-playbook
# oque executar: playbook.yml (arquivo criado na nossa pasta)
# o "-u" representa que passaremos o usuario, no caso da aula usamos "ubuntu"
# --private-key precisamos passar a nossa chave para acessar a maquina vitual
# por fim qual maquina ira fazer as configurações: -i hosts.yml (hosts é o arquivo atual!)